# Используем официальный образ Nginx как базовый
FROM nginx:alpine

# Копируем содержимое папки frontend (например, index.html) в директорию Nginx
COPY . /usr/share/nginx/html

# Открываем порт 80 для доступа
EXPOSE 80
