version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mts_test_fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
