"""upd

Revision ID: eeb483632aa0
Revises: 174640fed63d
Create Date: 2025-02-18 07:19:37.304408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb483632aa0'
down_revision: Union[str, None] = '174640fed63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('divisions_level_id_name_key', 'divisions', type_='unique')
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.drop_constraint('divisions_level_id_fkey', 'divisions', type_='foreignkey')
    op.drop_constraint('divisions_parent_id_fkey', 'divisions', type_='foreignkey')
    op.create_foreign_key(None, 'divisions', 'divisions', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'divisions', 'levels', ['level_id'], ['id'])
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employment_types_id'), 'employment_types', ['id'], unique=False)
    op.drop_index('idx_job_logs_created_at', table_name='job_logs')
    op.drop_index('idx_job_logs_job_id', table_name='job_logs')
    op.create_index(op.f('ix_job_logs_id'), 'job_logs', ['id'], unique=False)
    op.drop_constraint('job_logs_job_id_fkey', 'job_logs', type_='foreignkey')
    op.create_foreign_key(None, 'job_logs', 'jobs', ['job_id'], ['id'])
    op.drop_index('idx_jobs_division_id', table_name='jobs')
    op.drop_index('idx_jobs_employee_id', table_name='jobs')
    op.drop_index('idx_jobs_position_id', table_name='jobs')
    op.drop_index('idx_jobs_salary', table_name='jobs')
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_constraint('jobs_employment_type_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_employee_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_position_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_head_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_division_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'employees', ['head_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'employment_types', ['employment_type_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'divisions', ['division_id'], ['id'])
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.drop_constraint('positions_level_id_name_key', 'positions', type_='unique')
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.drop_constraint('positions_level_id_fkey', 'positions', type_='foreignkey')
    op.create_foreign_key(None, 'positions', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.create_foreign_key('positions_level_id_fkey', 'positions', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.create_unique_constraint('positions_level_id_name_key', 'positions', ['level_id', 'name'])
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_division_id_fkey', 'jobs', 'divisions', ['division_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jobs_head_id_fkey', 'jobs', 'employees', ['head_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('jobs_position_id_fkey', 'jobs', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jobs_employee_id_fkey', 'jobs', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jobs_employment_type_id_fkey', 'jobs', 'employment_types', ['employment_type_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.create_index('idx_jobs_salary', 'jobs', ['salary'], unique=False)
    op.create_index('idx_jobs_position_id', 'jobs', ['position_id'], unique=False)
    op.create_index('idx_jobs_employee_id', 'jobs', ['employee_id'], unique=False)
    op.create_index('idx_jobs_division_id', 'jobs', ['division_id'], unique=False)
    op.drop_constraint(None, 'job_logs', type_='foreignkey')
    op.create_foreign_key('job_logs_job_id_fkey', 'job_logs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_logs_id'), table_name='job_logs')
    op.create_index('idx_job_logs_job_id', 'job_logs', ['job_id'], unique=False)
    op.create_index('idx_job_logs_created_at', 'job_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_employment_types_id'), table_name='employment_types')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_constraint(None, 'divisions', type_='foreignkey')
    op.drop_constraint(None, 'divisions', type_='foreignkey')
    op.create_foreign_key('divisions_parent_id_fkey', 'divisions', 'divisions', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('divisions_level_id_fkey', 'divisions', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.create_unique_constraint('divisions_level_id_name_key', 'divisions', ['level_id', 'name'])
    # ### end Alembic commands ###
